//
//  Constants.swift
//  needletail-irc
//
//  Created by Cole M on 12/2/24.
//


public enum Constants: String, Sendable {
    case cLF = "\n"
    case cCR = "\r"
    case space = " "
    case hashTag = "#"
    case star = "*"
    case colon = ":"
    case comma = ","
    case bString = "b"
    case oString = "o"
    case plus = "+"
    case minus = "-"
    case atString = "@"
    case equalsString = "="
    case semiColon = ";"
    case none = ""
    case semiColonSpace = "; "
    case exclamation = "!"
    case underScore = "_"
    case ampersand = "&"
    case keys = "keys:"
    case nick = "NICK"
    case join = "JOIN"
    case join0 = "JOIN0"
    case part = "PART"
    case user = "USER"
    case privMsg = "PRIVMSG"
    case mode = "MODE"
    case kill = "KILL"
    case kick = "KICK"
    case dccChat = "DCCCHAT"
    case dccSend = "DCCSEND"
    case dccResume = "DCCRESUME"
    case sdccChat = "SDCCCHAT"
    case sdccSend = "SDCCSEND"
    case sdccResume = "SDCCRESUME"
    case registryRequest = "REGISTRYREQUEST"
    case registryResponse = "REGISTRYRESPONSE"
    case newDevice = "NEWDEVICE"
    case findUserConfig = "FINDUSERCONFIG"
    case offlineMessages = "OFFLINEMESSAGES"
    case deleteOfflineMessage = "DELETEOFFLINEMESSAGE"
    case pass = "PASS"
    case publishBlob = "PUBLISHBLOB"
    case readPublishedBlob = "READPUBLISHEDBLOB"
    case quit = "QUIT"
    case isOn = "ISON"
    case ping = "PING"
    case pong = "PONG"
    case list = "LIST"
    case notice = "NOTICE"
    case cap = "CAP"
    case whoIs = "WHOIS"
    case who = "WHO"
    case badgeUpdate = "BADGEUPDATE"
    case multipartMediaDownload = "MULTIPARTMEDIADOWNLOAD"
    case multipartMediaUpload = "MULTIPARTMEDIAUPLOAD"
    case listBucket = "LISTBUCKET"
    case requestMediaDeletion = "REQUESTMEDIADELETION"
    case destoryUser = "DESTROYUSER"
    case sQuit = "SQUIT"
    case server = "SERVER"
    case links = "LINKS"
}
